# Generated by Django 3.0.2 on 2020-02-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_userprofile_isverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
